version: '3.9'

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: 'swagger-editor'
    ports:
      - '8001:8080'

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: 'swagger-ui'
    ports:
      - '8002:8080'
    volumes:
      - ./api/swagger_bff_all_v3.yaml:/swagger_bff_all_v3.yaml
    environment:
      SWAGGER_JSON: /swagger_bff_all_v3.yaml

  swagger-api:
    image: stoplight/prism:3
    container_name: 'swagger-api'
    ports:
      - '8003:4010'
    command: mock -h 0.0.0.0 /swagger_bff_all_v3.yaml
    volumes:
      - ./api/swagger_bff_all_v3.yaml:/swagger_bff_all_v3.yaml
