module.exports = {
  DEVELOPMENT: true,
  APP_NAME: 'NuxtJs App',
  CLIENT_BASE_URL: 'http://example.com',
  SERVER_BASE_URL: 'http://127.0.0.1',
  GTM_ID: 'GTM-XXXXXXX',
  INS_AGENT_NO: 'littlefamily01',
  COGNITO_REGION: 'ap-northeast-1',
  COGNITO_CLIENT_ID: '4n566m02v9vhdei1nitvildogr',
  COGNITO_POOL_ID: 'ap-northeast-1_KxXKQHOh3',
  GMO_SHOP_ID: 'tshop00048268',
  WEBCAS_URL: '',
  INSURANCE_CLAIM_URL: '',
  HELP_URL: 'https://helpfeel.com/littlefamily-ec/',
};
