import { API_CREATE_PROPOSAL } from '~/api/contracts/API_CREATE_PROPOSAL';
import { API_FETCH_PROPOSAL } from '~/api/contracts/API_FETCH_PROPOSAL';
import { API_PREMIUM_CALCULATION } from '~/api/contracts/API_PREMIUM_CALCULATION';
import { API_FETCH_DOG_BREED } from '~/api/product/API_FETCH_DOG_BREED';
import { API_UPDATE_CUSTOMER } from '~/api/account/API_UPDATE_CUSTOMER';
import { API_GET_ACCOUNT_INFO } from '~/api/account/API_GET_ACCOUNT_INFO';
import { API_SAVE_CARD_INFO } from '~/api/policy/API_SAVE_CARD_INFO';
import { API_UPDATE_CARD_INFO } from '~/api/cs/API_UPDATE_CARD_INFO';
import { API_GET_CARD_INFO } from '~/api/query/API_GET_CARD_INFO';
import { API_CREATE_CONTRACT } from '~/api/policy/API_CREATE_CONTRACT';
import { API_FETCH_POLICY_INFO } from '~/api/policy/API_FETCH_POLICY_INFO';
import { API_UPDATE_PET_PHOTO } from '~/api/policy/API_UPDATE_PET_PHOTO';
import { API_UPLOAD_FILE } from '~/api/file/API_UPLOAD_FILE';
import { API_DOWNLOAD_FILE } from '~/api/file/API_DOWNLOAD_FILE';
import { API_CONFIRM_ACCEPTATION } from '~/api/policy/API_CONFIRM_ACCEPTATION';
import { API_GET_CONTRACT_INFO } from '~/api/query/API_GET_CONTRACT_INFO';
import { API_FETCH_DISEASE_CODE_MASTER } from '~/api/codemaster/API_FETCH_DISEASE_CODE_MASTER';
import { API_SAVE_DISEASE_HISTORY } from '~/api/policy/API_SAVE_DISEASE_HISTORY';

export {
  API_CREATE_PROPOSAL,
  API_PREMIUM_CALCULATION,
  API_FETCH_DOG_BREED,
  API_UPDATE_CUSTOMER,
  API_GET_ACCOUNT_INFO,
  API_SAVE_CARD_INFO,
  API_UPDATE_CARD_INFO,
  API_GET_CARD_INFO,
  API_CREATE_CONTRACT,
  API_FETCH_POLICY_INFO,
  API_UPDATE_PET_PHOTO,
  API_UPLOAD_FILE,
  API_DOWNLOAD_FILE,
  API_CONFIRM_ACCEPTATION,
  API_FETCH_PROPOSAL,
  API_GET_CONTRACT_INFO,
  API_FETCH_DISEASE_CODE_MASTER,
  API_SAVE_DISEASE_HISTORY,
};
